server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/hanu_minimart?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true&useSSL=false
    username: admin
    password: admin
    initialization-mode: always

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

app:
  tokenSecret: HanuMinimart180104
  tokenExpirationInMs: 864000000

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG